name: Build Flatpak Bundle
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flatpak
        run:
          |
          sudo apt -qq update
          sudo apt -qq install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install --noninteractive --arch=x86_64 org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
          git config --global protocol.file.allow always # https://github.com/flatpak/flatpak-builder/issues/495
      - name: Build
        run:
          |
          flatpak-builder --arch=x86_64 --install --user build com.alibabainc.DingTalk.yaml
          flatpak build-bundle --arch=x86_64 ~/.local/share/flatpak/repo/ com.alibabainc.DingTalk-x86_64.flatpak com.alibabainc.DingTalk

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle-x86_64
          path: com.alibabainc.DingTalk-x86_64.flatpak
  
  upload-release:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-bundle
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install xmlstarlet
        run: sudo apt -qq update && sudo apt -qq install -y xmlstarlet
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Get current date & version
        id: env
        run:
          |
          echo "CURRENT_DATE=$(date -u '+%y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "VERSION=$(xmlstarlet sel -t -v //component/releases/release[1]/@version com.alibabainc.DingTalk.metainfo.xml)" >> $GITHUB_OUTPUT
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.env.outputs.VERSION }}
          tag_name: ${{ steps.env.outputs.VERSION }}-${{ steps.env.outputs.CURRENT_DATE }}
          files: com.alibabainc.DingTalk-x86_64.flatpak
          body:
            |
            install via:
            ```
            flatpak install com.alibabainc.DingTalk-x86_64.flatpak
            ```
